// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfjcphiutmfhajursoly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmamNwaGl1dG1maGFqdXJzb2x5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NDYyMTUsImV4cCI6MjA2NzAyMjIxNX0.G_XZNSnaNKKPIXIDx3fQW74JKQz6cQ-onmelFFvngMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});